- hosts: kubernetes-cluster
  connection: ssh
  remote_user: root
  become: True
  gather_facts: False
  tasks:
   - name: Stop and disable firewalld.
     service:
       name: firewalld
       state: stopped
       enabled: False
